version: '3'

services:
  extension_for_test_dev:
    container_name: extension_for_test_dev
    build:
      context: .
    working_dir: /extension
    command: cextrun -d --no-rich-logging
    volumes: 
      - .:/extension
    env_file:
      - .extension_for_test_dev.env

  extension_for_test_bash:
    container_name: extension_for_test_bash
    build:
      context: .
    working_dir: /extension
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
    env_file:
      - .extension_for_test_dev.env

  extension_for_test_test:
    container_name: extension_for_test_test
    build:
      context: .
    working_dir: /extension
    command: extension-test
    volumes:
      - .:/extension
    env_file:
      - .extension_for_test_dev.env
